/**
 * Barcha yo'llar bitta joyda. Komponentlarda "/login" kabi qattiq string yozilmaydi,
 * ROUTES.login ishlatiladi. Parametrli yo'llar uchun funksiya: ROUTES.studentTopic(id).
 */
export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  selectCenter: "/select-center",
  changePassword: "/change-password",
  app: "/app",
  studentTasks: "/app/tasks",
  studentTask: (assignmentId: string) => `/app/tasks/${assignmentId}`,
  studentTests: "/app/tests",
  studentTestRun: (testId: string) => `/app/tests/${testId}`,
  studentAttemptResult: (attemptId: string) => `/app/attempts/${attemptId}`,
  studentTopic: (topicId: string) => `/app/topics/${topicId}`,
  studentInterview: "/app/interview",
  studentInterviewRun: (sessionId: string) => `/app/interview/${sessionId}`,
  studentBattle: "/app/battle",
  studentProfile: "/app/profile",
  teacher: "/teacher",
  teacherTasks: "/teacher/tasks",
  teacherStudents: "/teacher/students",
  teacherSettings: "/teacher/settings",
  teacherTask: (assignmentId: string) => `/teacher/tasks/${assignmentId}`,
  teacherStudentTwin: (studentId: string) => `/teacher/students/${studentId}/digital-twin`,
  superadmin: "/superadmin",
  superadminSettings: "/superadmin/settings",
  admin: "/admin",
  adminTasks: "/admin/tasks",
  adminStudents: "/admin/students",
  adminSettings: "/admin/settings",
  adminTask: (assignmentId: string) => `/admin/tasks/${assignmentId}`,
  adminStudentTwin: (studentId: string) => `/admin/students/${studentId}/digital-twin`,
  dev: {
    health: "/dev/health",
    uiKit: "/dev/ui",
  },
} as const;
