import {
  classDigitalTwinSchema,
  digitalTwinSchema,
  studentProgressSchema,
  type ClassDigitalTwin,
  type DigitalTwin,
  type StudentProgress,
} from "@zexn/shared";

export const classFixture: ClassDigitalTwin = classDigitalTwinSchema.parse({
  students: [
    {
      id: "student-namur",
      fullName: "Namur Umarov",
      login: "namur",
      overallMastery: 66,
      confidence: 0.75,
      weakestSkill: { id: "sk-state-immutability", name: "State immutability", mastery: 42 },
      activePatternCount: 2,
      atRisk: true,
      updatedAt: "2026-09-18T15:00:00.000Z",
    },
    {
      id: "student-malika",
      fullName: "Malika Raximova",
      login: "malika",
      overallMastery: 74,
      confidence: 0.8,
      weakestSkill: { id: "sk-effects", name: "useEffect", mastery: 58 },
      activePatternCount: 1,
      atRisk: false,
      updatedAt: "2026-09-18T12:20:00.000Z",
    },
    {
      id: "student-sardor",
      fullName: "Sardor Karimov",
      login: "sardor",
      overallMastery: 82,
      confidence: 0.9,
      weakestSkill: { id: "sk-forms", name: "Formalar", mastery: 69 },
      activePatternCount: 0,
      atRisk: false,
      updatedAt: "2026-09-17T16:40:00.000Z",
    },
    {
      id: "student-aziza",
      fullName: "Aziza Qodirova",
      login: "aziza",
      overallMastery: null,
      confidence: 0,
      weakestSkill: null,
      activePatternCount: 0,
      atRisk: false,
      updatedAt: null,
    },
  ],
  studentsAtRisk: 1,
  commonWeakSkills: [
    {
      skillId: "sk-state-immutability",
      name: "State immutability",
      studentCount: 2,
      avgMastery: 49,
    },
  ],
  commonPatterns: [
    {
      patternId: "pat-direct-state",
      code: "DIRECT_STATE_MUTATION",
      name: "Direct State Mutation",
      studentCount: 2,
    },
  ],
  recommendedActions: [
    {
      type: "GROUP_LESSON",
      skillId: "sk-state-immutability",
      skillName: "State immutability",
      text: "State immutability bo'yicha 15 daqiqalik umumiy mashg'ulot o'tkazing.",
    },
    {
      type: "TARGETED_TASKS",
      skillId: "sk-state-immutability",
      skillName: "State immutability",
      text: "Xato patterni bor o'quvchilarga maqsadli vazifa yuboring.",
    },
  ],
});

/**
 * Namur Umarov uchun SDT fixture (T-016 talablariga muvofiq).
 * Server tayyor bo'lmaganda VITE_TWIN_FIXTURE=true bilan ishlaydi.
 */
export const fixtureDigitalTwin: DigitalTwin = digitalTwinSchema.parse({
  student: {
    id: "student-namur",
    fullName: "Namur Umarov",
    login: "namur",
  },
  course: {
    id: "course-react",
    title: "Frontend React",
    level: "React Beginner",
  },
  overallMastery: 66,
  confidence: 0.75,
  summary: "JSX va Props yaxshi. State immutability va Shartli rendering'da bo'shliq bor.",
  strongSkills: [
    {
      id: "sk-jsx",
      key: "jsx",
      name: "JSX",
      topicId: "top-jsx",
      topicTitle: "JSX asoslari",
      mastery: 92,
      confidence: 0.9,
      attempts: 8,
      tier: "strong",
      lastActivityAt: "2026-09-14T09:00:00.000Z",
    },
    {
      id: "sk-props",
      key: "props",
      name: "Props",
      topicId: "top-props",
      topicTitle: "Komponentlar va Props",
      mastery: 86,
      confidence: 0.85,
      attempts: 7,
      tier: "strong",
      lastActivityAt: "2026-09-15T10:15:00.000Z",
    },
  ],
  developingSkills: [
    {
      id: "sk-lists",
      key: "lists-keys",
      name: "Lists & Keys",
      topicId: "top-lists",
      topicTitle: "Ro'yxatlar bilan ishlash",
      mastery: 68,
      confidence: 0.75,
      attempts: 5,
      tier: "developing",
      lastActivityAt: "2026-09-16T16:45:00.000Z",
    },
    {
      id: "sk-events",
      key: "events",
      name: "Events",
      topicId: "top-events",
      topicTitle: "Hodisalarni boshqarish",
      mastery: 64,
      confidence: 0.7,
      attempts: 4,
      tier: "developing",
      lastActivityAt: "2026-09-16T18:00:00.000Z",
    },
  ],
  weakSkills: [
    {
      id: "sk-conditional",
      key: "conditional-rendering",
      name: "Conditional Rendering",
      topicId: "top-conditional",
      topicTitle: "Shartli renderlash",
      mastery: 55,
      confidence: 0.65,
      attempts: 4,
      tier: "weak",
      lastActivityAt: "2026-09-17T11:20:00.000Z",
    },
    {
      id: "sk-state",
      key: "state",
      name: "State",
      topicId: "top-state",
      topicTitle: "useState hooki",
      mastery: 58,
      confidence: 0.6,
      attempts: 3,
      tier: "weak",
      lastActivityAt: "2026-09-17T15:10:00.000Z",
    },
    {
      id: "sk-state-immutability",
      key: "state-immutability",
      name: "State Immutability",
      topicId: "top-state",
      topicTitle: "State o'zgarmasligi",
      mastery: 42,
      confidence: 0.8,
      attempts: 6,
      tier: "weak",
      lastActivityAt: "2026-09-18T14:30:00.000Z",
    },
  ],
  unassessedSkills: [
    {
      id: "sk-components",
      key: "components",
      name: "Components",
      topicId: "top-components",
      topicTitle: "Komponent arxitekturasi",
      mastery: 50,
      confidence: 0,
      attempts: 0,
      tier: "unassessed",
      lastActivityAt: null,
    },
    {
      id: "sk-forms",
      key: "forms",
      name: "Forms",
      topicId: "top-forms",
      topicTitle: "Formalar bilan ishlash",
      mastery: 50,
      confidence: 0,
      attempts: 0,
      tier: "unassessed",
      lastActivityAt: null,
    },
    {
      id: "sk-use-effect",
      key: "use-effect",
      name: "useEffect",
      topicId: "top-use-effect",
      topicTitle: "Yon ta'sirlar va useEffect",
      mastery: 50,
      confidence: 0,
      attempts: 0,
      tier: "unassessed",
      lastActivityAt: null,
    },
    {
      id: "sk-api-fetching",
      key: "api-fetching",
      name: "API Fetching",
      topicId: "top-api",
      topicTitle: "Ma'lumotlarni yuklash",
      mastery: 50,
      confidence: 0,
      attempts: 0,
      tier: "unassessed",
      lastActivityAt: null,
    },
  ],
  activePatterns: [
    {
      id: "sp-1",
      patternId: "pat-direct-state",
      code: "DIRECT_STATE_MUTATION",
      name: "Direct State Mutation",
      description:
        "State obyektini yoki massivini to'g'ridan-to'g'ri o'zgartirish (state.push yoki state.x = y).",
      skillId: "sk-state-immutability",
      skillName: "State Immutability",
      occurrences: 3,
      resolvedCount: 0,
      status: "ACTIVE",
      lastDetectedAt: "2026-09-18T14:30:00.000Z",
    },
    {
      id: "sp-2",
      patternId: "pat-missing-key",
      code: "MISSING_KEY_PROP",
      name: "Missing Key Prop",
      description: "Massiv elementlarini render qilishda key prop ko'rsatilmagan.",
      skillId: "sk-lists",
      skillName: "Lists & Keys",
      occurrences: 2,
      resolvedCount: 0,
      status: "ACTIVE",
      lastDetectedAt: "2026-09-17T11:20:00.000Z",
    },
  ],
  resolvedPatterns: [],
  nextSteps: [
    {
      id: "step-1",
      skillId: "sk-state-immutability",
      skillName: "State Immutability",
      actionType: "TARGETED_TASK",
      priority: 3,
      reason: "Direct state mutation 3 marta aniqlangan va mastery 42%",
      instruction:
        "State immutability bo'yicha 3 ta amaliy mashqni bajaring va spread operatordan foydalaning.",
      status: "pending",
      assignmentId: null,
      createdAt: "2026-09-18T15:00:00.000Z",
    },
    {
      id: "step-2",
      skillId: "sk-conditional",
      skillName: "Conditional Rendering",
      actionType: "RETEST",
      priority: 2,
      reason: "Mastery 55% ga tushib ketgan",
      instruction: "Ternar operatori va mantiqiy && bo'yicha mini-testdan o'ting.",
      status: "pending",
      assignmentId: null,
      createdAt: "2026-09-17T12:00:00.000Z",
    },
  ],
  recentProgress: [
    {
      id: "prog-1",
      skillId: "sk-state-immutability",
      skillName: "State Immutability",
      previousScore: 48,
      newScore: 42,
      source: "SUBMISSION",
      label: "Vazifada to'g'ridan-to'g'ri state o'zgartirildi",
      createdAt: "2026-09-18T14:30:00.000Z",
    },
    {
      id: "prog-2",
      skillId: "sk-conditional",
      skillName: "Conditional Rendering",
      previousScore: 60,
      newScore: 55,
      source: "ATTEMPT",
      label: "Testda shartli render xatosi",
      createdAt: "2026-09-17T11:20:00.000Z",
    },
    {
      id: "prog-3",
      skillId: "sk-lists",
      skillName: "Lists & Keys",
      previousScore: 62,
      newScore: 68,
      source: "SUBMISSION",
      label: "Ro'yxat vazifasi muvaffaqiyatli qabul qilindi",
      createdAt: "2026-09-16T16:45:00.000Z",
    },
    {
      id: "prog-4",
      skillId: "sk-props",
      skillName: "Props",
      previousScore: 80,
      newScore: 86,
      source: "REVIEW",
      label: "Props bo'yicha mustaqil ish (86 ball)",
      createdAt: "2026-09-15T10:15:00.000Z",
    },
    {
      id: "prog-5",
      skillId: "sk-jsx",
      skillName: "JSX",
      previousScore: 88,
      newScore: 92,
      source: "ATTEMPT",
      label: "JSX sintaksis testi topshirildi",
      createdAt: "2026-09-14T09:00:00.000Z",
    },
  ],
  updatedAt: "2026-09-18T15:00:00.000Z",
});

export const fixtureStudentProgress: StudentProgress = studentProgressSchema.parse({
  skills: [
    {
      skillId: "sk-state-immutability",
      skillName: "State Immutability",
      points: [
        {
          score: 48,
          source: "SEED",
          label: "Boshlang'ich baho",
          createdAt: "2026-09-10T10:00:00.000Z",
        },
        {
          score: 42,
          source: "SUBMISSION",
          label: "Vazifada to'g'ridan-to'g'ri state o'zgartirildi",
          createdAt: "2026-09-18T14:30:00.000Z",
        },
      ],
    },
  ],
});
